# Build stage
FROM golang:1.21.0-alpine3.17 AS build

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Change the working directory to /app/cmd/blockservice/
WORKDIR /app/cmd/blockservice/

# Build the Go application named 'main'
RUN go build -o main .

# Alpine Run stage
# Run stage
FROM alpine:latest

# Install tcpdump package
RUN apk --no-cache add tcpdump

# Set the working directory to /app
WORKDIR /app

# Copy the built executable from the build stage to /app
COPY --from=build /app/cmd/blockservice/main .

# Specify the command to run on container start
CMD ["./main"]
