version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blocks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
